---
- name: "Install python packages"
  pip:
    name: "{{ python_packages }}"
    state: "{{ desired_state }}"
    extra_args: "--user"
    executable: "pip3"
  tags:
    - dependency
    - install
    - python
